### ISSUE TITLE
Issue with duplicate names with different values?

### ISSUE THREAD

**Issue by CarmenAPuccio** [fraenki/puppet-proftpd#1]
I don't know if this is something I'm doing wrong in Hiera or it's an issue with the module. It only takes the last of the values when they have the same name in the config. For example try this in Hiera:
---
proftpd::default_config: false
proftpd::load_modules:
  sql: {}
  sql_mysql: {}
  quotatab: {}
  quotatab_sql: {}

proftpd::options:
  ROOT:
    ServerName: 'Test'
    ServerAdmin: 'root@localhost'
    DefaultServer: 'on'
    UseReverseDNS: 'off'
    LogFormat: 'default  "%h %l %u %t \"%r\" %s %b"'
    LogFormat: 'auth     "%v [%P] %h %t \"%r\" %s"'

Notice it'll only save the LogFormat auth and not the default. I have a bunch more in mysql for Hiera that have the same issue (only keeps the last). It even calls it out in his docs that you can do it so what am I missing?

Grep results post puppet apply in CentOS 7

[vagrant@localhost etc]$ more proftpd.conf | grep Log
LogFormat auth     "%v [%P] %h %t \"%r\" %s"

**Comment by fraenki** [comment]
@CarmenAPuccio Thanks for your report! Actually this was a documentation bug, and was also present in the default configuration. You need to specify these value as an array:

```json
LogFormat:
  - 'default "%h %l %u %t \"%r\" %s %b"'
  - 'auth "%v [%P] %h %t \"%r\" %s"'
```

This is fixed in v1.1.1.
