### ISSUE TITLE
please release current version (including june 2016 commits) on the forge

### ISSUE THREAD

**Issue by lesinigo** [fraenki/puppet-proftpd#13]
The version currently published on Puppet Forge (v1.4.2) has some dependency bug that prevents it from running, at least when used on Ubuntu 16.04 with Puppet4 and current version of all dependencies (concat 2.2.0, stdlib 4.12.0).

The current master branch as of this writing seems to work correctly (we are checking it out with R10k directly from github).

Please release this as a new version to ease usage for people coming on the forge and using `puppet module install`.

**Comment by fraenki** [comment]
Done :)
