### ISSUE TITLE
Issue with example config 

### ISSUE THREAD

**Issue by lmorfitt** [fraenki/puppet-proftpd#3]
Hello,

I'm having an issue with the example within the readme. The below code causes a error, which I've been unable to debug. Any suggestions please?

```puppet
class profiles::ftp_server {

class { 'proftpd':
  options => {
    ROOT  => {
      ServerName   => 'FTP server',
      MaxInstances => '10',
    },
    'IfModule mod_vroot.c' => {
      VRootEngine => 'on',
    },
  },
}

}


```

```bash
puppet apply --modulepath=/etc/puppet/modules/ -e 'include profiles::ftp_server' 

Error: Syntax error at 'ROOT'; expected '}' at /etc/puppet/modules/profiles/manifests/ftp_server.pp:6 on node
```

Thanks,
Luke

**Comment by mrh666** [comment]
Confirmed,

```
class { 'proftpd':
  options => {
    ROOT  => {
      ServerName   => 'FTP server',
      MaxInstances => '10',
    },
    'IfModule mod_vroot.c' => {
      VRootEngine => 'on',
    },
  },
}
```

Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Syntax error at 'ROOT'; expected '}' at /etc/puppet/environments/common/ftpbd/manifests/init.pp:6 on node ftpbd-c80qggvfbzkfkvc

**Comment by fraenki** [comment]
Thanks for reporting this issue!

I have to admit that I've never tested the non-hiera example. Sorry about that. It was a matter of proper quoting. I've fixed the documentation and released a new version along with other bugfixes.
