### ISSUE TITLE
Support for Puppet 6

### ISSUE THREAD

**Issue by abegosum** [fraenki/puppet-proftpd#35]
This module is currently marked as being compatible with Puppet < 6.  Considering there aren't a large number of dependencies listed, could this be tested on Puppet 6 and updated to be compatible?

**Comment by fraenki** [comment]
Sure, I'll update the tests and will prepare a new release soon.

**Comment by abegosum** [comment]
Fantastic.  And thanks for your work on this!  We heavily utilize this module.

**Comment by fraenki** [comment]
Version 2.0.0 is now available.
