### ISSUE TITLE
Package change since Debian Bullseye

### ISSUE THREAD

**Issue by jbender81** [fraenki/puppet-proftpd#38]
Hi,
The "main" package for proftpd has been changed on Debian Bullseye, and onwards, to "proftpd-core" instead of "proftpd-basic".
"proftpd-basic" is, at least in Bullseye, Bookworm and (current) Sid, still available as transitional package, but it would be nicer to have the actual main package installed instead just as dependency.

Cheers
Jörg

**Comment by fraenki** [comment]
Could you submit a pull request? :)

**Comment by jbender81** [comment]
https://github.com/fraenki/puppet-proftpd/pull/40

**Comment by saz** [comment]
@fraenki As #40 has been merged, I guess this issue can be closed.

**Comment by fraenki** [comment]
@saz True, thanks for the reminer :blush:
